# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KukuFire2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KukuFire2
  pod 'Firebase/Core'
  
  target 'KukuFire2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'KukuFire2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for KukuFire2-tvOS

  target 'KukuFire2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
